### ISSUE TITLE
High CPU when editing Vue SFC template

### ISSUE THREAD

**Issue by tony19** [vuedx/languagetools#162]
**Describe the bug**
Editing an SFC template causes an exception in VS Code (shown below) followed by non-stop console logs of `Is vue-html supported? true`:

```
console.ts:137 [Extension Host] Error: Cannot find module 'vue/package.json'
Require stack:
  - /Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js
  - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
  - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
  - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
      at Function.r.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:406)
      at requireFileFromPackage (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:127979:28)
      at getPackageJSON (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:127956:16)
      at InferredVueProject.loadVueVersion (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:128187:31)
      at new VueProject (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:128158:14)
      at new InferredVueProject (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:128277:9)
      at DocumentService.getProjectForFile (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:134356:15)
      at AsyncDocumentStore.resolve (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:134305:34)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
      at async AsyncDocumentStore.load (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:132972:26)
      at async DocumentService.asVueDocument (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:134339:21)
      at async TemplateLanguageProxy.getDocumentAt (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:134219:26)
      at async TemplateLanguageProxy.provideCompletionItems (/Users/tony/.vscode/extensions/znck.vue-language-features-0.5.0/dist/index.js:134207:26)
      at async H.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:764:28)
```

**To Reproduce**
1. Using Vue CLI, create a default Vue 2 project, and open in VS Code:

```
vue create my-project --default
code my-project
```
2. Open VS Code's DevTools console via menu (`Help > Toggle Developer Tools`), and open the *Console* tab.
3. Open `<root>/src/App.vue`.
4. In the `<template>`, type `d` (for `div`).
5. Observe the resulting high CPU utilization (250%), the exception shown in the DevTools console, and the non-stop logging of `Is vue-html supported? true`.
6. Close the editor tab for `<root>/src/App.vue`.
7. Observe the symptoms are still not resolved.

**Expected behavior**
SFC templates can be edited without high CPU utilization and without non-stop logging.

**Screenshots/Recording**

<img width="724" alt="Screen Shot 2021-01-15 at 10 07 13 PM" src="https://user-images.githubusercontent.com/26580/104796698-429ccc00-577e-11eb-9902-b170ac5a8a8a.png">

**Info (please complete the following information):**
 - macOS Big Sur 11.1
 - VS Code 1.52.1
 - TypeScript: *(not used)*
 - Vue 2.6.12
 - VueDX 0.5.0
 - Vetur 0.31.3
 - Node 14.9.0
 - npm 6.14.8

**Additional context**
*N/A*

**Comment by EngHell** [comment]
@znck Steps to build the extension from source would be apreciated, since I just installed the extension on vscode and the issue persist, as well this could enable anyone to send PR's faster.

**Comment by znck** [comment]
https://github.com/znck/vue-developer-experience/blob/master/CONTRIBUTING.md
