### ISSUE TITLE
Can not found global component

### ISSUE THREAD

**Issue by pincman** [vuedx/languagetools#195]
**Describe the bug**
<img width="461" alt="截屏2021-02-07 上午8 29 40" src="https://user-images.githubusercontent.com/74093067/107132962-b5810900-691e-11eb-8fe8-8d089880dbeb.png">

**To Reproduce**

**Expected behavior**

**Screenshots/Recording**

**Info (please complete the following information):**
 - OS [Mac]
 - IDE [VS Code]
 - TypeScript Version [4.0.1]
 - 3.0.1
 - Antd vue

**Additional context**
Add any other context about the problem here e.g. code snippets or reproduction repository etc.

**Comment by Ti-webdev** [comment]
even with `samples/feature-vue-project-inferred` it does not work(

@znck 
It's throw an error on  `<GlobalComponent />`:
```
 ERR <semantic> TypeScript Server Error (4.2.3)
Could not find source file: '/home/ti/pj/vue-developer-experience/samples/feature-vue-project-inferred/src/App.vue_________render.tsx'.
Error: Could not find source file: '/home/ti/pj/vue-developer-experience/samples/feature-vue-project-inferred/src/App.vue_________render.tsx'.
    at getValidSourceFile (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149001:29)
    at Proxy.getDefinitionAndBoundSpan (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:149310:73)
    at withTeleports (/home/ti/.vscode/extensions/johnsoncodehk.volar-0.24.0/node_modules/@volar/vscode-vue-languageservice/out/tsPluginApis.js:84:52)
    at Proxy.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/johnsoncodehk.volar-0.24.0/node_modules/@volar/vscode-vue-languageservice/out/tsPluginApis.js:76:9)
    at Object.apply (/home/ti/.vscode/extensions/johnsoncodehk.volar-0.24.0/node_modules/@volar/vscode-vue-languageservice/out/languageService.js:223:31)
    at Object.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/znck.vue-language-features-0.6.3/node_modules/@vuedx/typescript-standalone/dist/index.js:156157:32)
    at Object.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/znck.vue-language-features-0.6.3/node_modules/@vuedx/typescript-standalone/dist/index.js:156503:41)
    at Object.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/znck.vue-language-features-0.6.3/node_modules/@vuedx/typescript-standalone/dist/index.js:156882:45)
    at Object.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/znck.vue-language-features-0.6.3/node_modules/@vuedx/typescript-standalone/dist/index.js:145798:27)
    at Object.getDefinitionAndBoundSpan (/home/ti/.vscode/extensions/znck.vue-language-features-0.6.3/node_modules/@vuedx/typescript-standalone/dist/index.js:157209:45)
    at IOSession.Session.getDefinitionAndBoundSpan (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159853:83)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:159116:61)
    at /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:88
    at IOSession.Session.executeWithRequestId (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160954:28)
    at IOSession.Session.executeCommand (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160963:33)
    at IOSession.Session.onMessage (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:160989:35)
    at Interface.<anonymous> (/opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:163650:31)
    at Interface.emit (events.js:315:20)
    at Interface.EventEmitter.emit (domain.js:483:12)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23): Error: <semantic> TypeScript Server Error (4.2.3)
    ```
