### ISSUE TITLE
TS Server fatal error: Cannot read property 'getSourceFiles' of undefined

### ISSUE THREAD

**Issue by victorlmneves** [vuedx/languagetools#271]
**TypeScript Version:** 4.6.3

**Steps to reproduce crash**
1. Open any project that uses Typescript

Besides this one, I also get another message saying that the service died 5 times and when I click to report an Issue it displays this message, but as can see from the details that's the version I'm using
<img width="545" alt="image" src="https://user-images.githubusercontent.com/17341789/160243740-c62a771c-f304-4b04-902c-f9789cb7d832.png">

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`
```
TypeError: Cannot read property 'getSourceFiles' of undefined
    at ConfiguredProject.Project.getScriptInfos (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:166614:44)
    at ProjectService.sendProjectTelemetry (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:169477:66)
    at ConfiguredProject.updateGraph (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:167831:37)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:169551:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170634:44)
    at /Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170974:97
    at Object.flatMap (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:508:25)
    at ProjectService.applyChangesInOpenFiles (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:170974:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:172133:46)
    at /Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174069:88
    at IpcIOSession.Session.executeWithRequestId (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174060:28)
    at IpcIOSession.Session.executeCommand (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174069:33)
    at IpcIOSession.Session.onMessage (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:174095:35)
    at process.<anonymous> (/Users/victorneves/_mycode/new-victorneves.dev/node_modules/typescript/lib/tsserver.js:176730:31)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|156, 67, 40|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id f44da19d-6f59-4732-8d39-f15f3439850d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by znck** [comment]
Need more information. Can you share file or project that causes this issue?
